sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kube2422/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kube2422/docker-react npm run test -- --coverage
